package ch.appropppo.greendao.srcgen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import ch.appropppo.greendao.srcgen.Person;
import ch.appropppo.greendao.srcgen.Address;

import ch.appropppo.greendao.srcgen.PersonDao;
import ch.appropppo.greendao.srcgen.AddressDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig addressDaoConfig;

    private final PersonDao personDao;
    private final AddressDao addressDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        addressDaoConfig = daoConfigMap.get(AddressDao.class).clone();
        addressDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        addressDao = new AddressDao(addressDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(Address.class, addressDao);
    }
    
    public void clear() {
        personDaoConfig.getIdentityScope().clear();
        addressDaoConfig.getIdentityScope().clear();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public AddressDao getAddressDao() {
        return addressDao;
    }

}
